{% set name = "CheckM2" %}
{% set version = "1.1.0" %}
{% set sha256 = "7978e4ca08ae8ea3285931b955d1a4818684f9f955995837e98e6ab7ff90674f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chklovski/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script:
    - sed -i.bak 's|find_packages|find_namespace_packages|g' setup.py
    - rm -f *.bak
    - {{ PYTHON }} -m pip install . --no-build-isolation --no-deps --no-cache-dir -vvv
  entry_points:
    - checkm2 = checkm2.main:main
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools
  run:
    - python >=3.12
    - scikit-learn >=1.6.1
    - numpy
    - diamond >=2.1.11
    # https://github.com/bioconda/bioconda-recipes/issues/69866
    - tensorflow >=2.17,<2.20
    - lightgbm
    - pandas
    - scipy
    - prodigal >=2.6.3
    - requests
    - packaging
    - tqdm
    - keras

test:
  commands:
    - checkm2 --help

about:
  home: "https://github.com/chklovski/CheckM2"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE
  summary: "Assessing the quality of metagenome-derived genome bins using machine learning."
  dev_url: "https://github.com/chklovski/CheckM2"
  doc_url: "https://github.com/chklovski/CheckM2/blob/{{ version }}/README.md"

extra:
  notes: "CheckM2 requries the DIAMOND database that can be downloaded with `checkm2 database --download`."
  recipe-maintainers:
    - chklovski
  identifiers:
    - biotools:checkm2
    - usegalaxy-eu:checkm2
    - doi:10.1038/s41592-023-01940-w
